cc_library(
	name="MatConvFPGA",
	srcs = ["libMatConvFPGA.so"],
	hdrs = glob(["*.h"]),
	visibility=["//visibility:public"],
)

cc_library(
        name="Conv2DFPGA",
        srcs = ["libConv2DFPGA.so"],
        hdrs = glob(["*.h"]),
        visibility=["//visibility:public"],
)
